#
# package: github.com/asydevc/db.
# template: db
#
# [driver]
# [dsn]
# [max-idle]
# [max-open]
# [max-lifetime]
# [mapper]
#
driver: "mysql"
dsn:
  - "root:pass@tcp(127.0.0.1:3306)/cn_udm_sync?charset=utf8"
#  - "develop:develop123@tcp(udtest.turboradio.cn:6033)/cn_udm_sync?charset=utf8"
max-idle: 16
max-open: 128
max-lifetime: 60
mapper: "snake"
